# -- coding: utf-8 --

# Form implementation generated from reading ui file 'selectd.ui'
#
# Created by: PyQt6 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class RegisterForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(519, 207)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditUsername = QtWidgets.QLineEdit(Form)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.horizontalLayout_2.addWidget(self.lineEditUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditPassword = QtWidgets.QLineEdit(Form)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout_3.addWidget(self.lineEditPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditNama = QtWidgets.QLineEdit(Form)
        self.lineEditNama.setObjectName("lineEditNama")
        self.horizontalLayout_4.addWidget(self.lineEditNama)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")

        # connected clicked signal of button with insert_data method
        self.pushButton.clicked.connect(self.insert_data)
        self.verticalLayout.addWidget(self.pushButton)
        self.labelResult = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


# inserting data to codeloop database in wampserver


    def insert_data(self):
        try:
            mydb = mc.connect(

                host="localhost",
                user="root",
                password="",
                database="codeloop"
            )

            mycursor = mydb.cursor()

            # id = self.lineEditId.text()
            username = self.lineEditUsername.text()
            password = self.lineEditPassword.text()
            nama = self.lineEditNama.text()

            sql = "INSERT INTO user (username, password, nama) VALUES (%s, %s, %s)"
            val = (username, password, nama)

            mycursor.execute(sql, val)

            mydb.commit()
            self.labelResult.setText("Registrasi Berhasil")

        except mc.Error as e:
            self.labelResult.setText("Registrasi gagal")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Registrasi"))
        self.label_2.setText(_translate("Form", "Username : "))
        self.label_3.setText(_translate("Form", "Password : "))
        self.label_4.setText(_translate("Form", "Nama : "))
        self.pushButton.setText(_translate("Form", "Registrasi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = RegisterForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
