# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert.ui'
#
# Created by: PyQt6 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(519, 207)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditNim = QtWidgets.QLineEdit(Form)
        self.lineEditNim.setObjectName("lineEditNim")
        self.horizontalLayout.addWidget(self.lineEditNim)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditNama = QtWidgets.QLineEdit(Form)
        self.lineEditNama.setObjectName("lineEditNama")
        self.horizontalLayout_2.addWidget(self.lineEditNama)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditTempat = QtWidgets.QLineEdit(Form)
        self.lineEditTempat.setObjectName("lineEditTempat")
        self.horizontalLayout_3.addWidget(self.lineEditTempat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditTanggal = QtWidgets.QLineEdit(Form)
        self.lineEditTanggal.setObjectName("lineEditTanggal")
        self.horizontalLayout_4.addWidget(self.lineEditTanggal)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEditAlamat = QtWidgets.QLineEdit(Form)
        self.lineEditAlamat.setObjectName("lineEditAlamat")
        self.horizontalLayout_5.addWidget(self.lineEditAlamat)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")

        # connected clicked signal of button with insert_data method
        self.pushButton.clicked.connect(self.insert_data)
        self.verticalLayout.addWidget(self.pushButton)
        self.labelResult = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


# inserting data to codeloop database in wampserver

    def insert_data(self):
        try:
            mydb = mc.connect(

                host="localhost",
                user="root",
                password="",
                database="codeloop"
            )

            mycursor = mydb.cursor()

            nim = self.lineEditNim.text()
            nama = self.lineEditNama.text()
            tempat_lahir = self.lineEditTempat.text()
            tanggal_lahir = self.lineEditTanggal.text()
            alamat = self.lineEditAlamat.text()

            sql = "INSERT INTO siswa (nim, nama, tempat_lahir, tanggal_lahir, alamat) VALUES (%s, %s, %s, %s, %s)"
            val = (nim, nama, tempat_lahir, tanggal_lahir, alamat)

            mycursor.execute(sql, val)

            mydb.commit()
            self.labelResult.setText("Data Inserted")

        except mc.Error as e:
            self.labelResult.setText("Error Inserting Data")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nim"))
        self.label_2.setText(_translate("Form", "Nama"))
        self.label_3.setText(_translate("Form", "Tempat Lahir"))
        self.label_4.setText(_translate("Form", "Tanggal Lahir"))
        self.label_5.setText(_translate("Form", "Alamat"))
        self.pushButton.setText(_translate("Form", "Insert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
